---
apiVersion: v1
kind: Service
metadata:
  name: downstream
  labels:
    app: downstream
spec:
  ports:
  - port: 30001
    name: grpc-downstream
  selector:
    app: downstream
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: downstream-v1
  labels:
    version: v1
spec:
  replicas: 1
  selector:
      matchLabels:
          app: downstream
  template:
    metadata:
      labels:
        app: downstream
        version: v1
    spec:
      containers:
      - name: downstream
        {{if .duat.awsecr}}
        image: {{.duat.awsecr}}/platform-services/{{.duat.module}}:{{.duat.version}}
        imagePullPolicy: Always
        {{else}}
        image: downstream:{{.duat.version}}
        imagePullPolicy: Never
        {{end}}
        ports:
        - containerPort: 30001
          name: grpc-downstream
        env:
        - name: "LOGXI_FORMAT"
          value: "happy,maxcol=1024"
        - name: "LOGXI"
          value: "*=TRC"
        - name: "IP_PORT"
          value: ":30001,0.0.0.0:30001"
        - name: "O11Y_KEY"
          valueFrom:
            secretKeyRef:
              name: honeycomb-key
              key: apikey
        - name: "O11Y_DATASET"
          valueFrom:
            secretKeyRef:
              name: honeycomb-key
              key: dataset
        resources:
            requests:
                memory: "256Mi"
                cpu: "100m"
            limits:
                memory: "512Mi"
                cpu: "100m"
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: "downstream-client-mtls"
spec:
  host: downstream
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
